# Generated by Django 5.0.3 on 2024-03-24 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=200)),
                ('nascimento_paciente', models.DateField()),
                ('telefone_paciente', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000)])),
                ('nome_mãe', models.CharField(max_length=200)),
                ('telefone_mãe', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000)])),
                ('nome_pai', models.CharField(max_length=200)),
                ('telefone_pai', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000)])),
                ('início_tratamento', models.DateField()),
                ('término_tratamento', models.DateField()),
                ('endereço', models.CharField(max_length=300)),
                ('número', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000)])),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(default='SP', max_length=2)),
            ],
        ),
    ]
