# Generated by Django 5.0.3 on 2024-03-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendaPsico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='número',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone_mãe',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone_paciente',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone_pai',
            field=models.CharField(max_length=11),
        ),
    ]
