# Generated by Django 5.0.3 on 2024-03-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendaPsico', '0002_alter_paciente_número_alter_paciente_telefone_mãe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cidade',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='endereço',
            field=models.CharField(default='null', max_length=300),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='início_tratamento',
            field=models.DateField(default='null'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nascimento_paciente',
            field=models.DateField(default='null'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_mãe',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_pai',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='número',
            field=models.CharField(default='null', max_length=11),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone_mãe',
            field=models.CharField(default='null', max_length=11),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone_paciente',
            field=models.CharField(default='null', max_length=11),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone_pai',
            field=models.CharField(default='null', max_length=11),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='término_tratamento',
            field=models.DateField(default='null'),
        ),
    ]
