# Generated by Django 5.0.3 on 2024-03-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendaPsico', '0004_alter_paciente_cidade_alter_paciente_endereço_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='início_tratamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='término_tratamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
