# Generated by Django 5.0.3 on 2024-03-26 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendaPsico', '0005_alter_paciente_início_tratamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anotação',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anotação', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendaPsico.paciente')),
            ],
        ),
    ]
