# Generated by Django 5.0.3 on 2024-03-26 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendaPsico', '0006_anotação'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotação',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='agendaPsico.paciente'),
        ),
    ]
