# Generated by Django 5.0.3 on 2024-03-27 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendaPsico', '0008_delete_anotação'),
    ]

    operations = [
    ]
