# Generated by Django 5.0.3 on 2024-03-29 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendaPsico', '0010_anotação'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='nome_mãe',
            new_name='responsável',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nome_pai',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefone_mãe',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefone_pai',
        ),
    ]
