# Generated by Django 5.0.3 on 2024-03-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendaPsico', '0011_rename_nome_mãe_paciente_responsável_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='responsável',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
