# Generated by Django 5.0.3 on 2024-04-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendaPsico', '0013_alter_paciente_responsável'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.TextField(blank=True, null=True)),
                ('data_tarefa', models.DateField(blank=True, null=True)),
                ('título_anotação', models.TextField(blank=True, max_length=300, null=True)),
                ('anotação_texto', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
