# Generated by Django 5.0.3 on 2024-04-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendaPsico', '0014_agenda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='anotação_texto',
            new_name='texto_anotação',
        ),
        migrations.AddField(
            model_name='agenda',
            name='data_anotação',
            field=models.DateField(blank=True, null=True),
        ),
    ]
