# Generated by Django 5.0.3 on 2024-04-06 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendaPsico', '0015_rename_anotação_texto_agenda_texto_anotação_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='data_anotação',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='texto_anotação',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='título_anotação',
        ),
    ]
